### PR TITLE
pin Python >=3.7 for the 4.2.0 release

### LINKED ISSUE #29: 4.2.0 no longer supports py36
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It looks like the newest version of `typing_extensions` no longer supports py36

https://github.com/python/typing/commit/9a39406fa45fbfa76eb5d35afb7863f5f727ad87

But that was not reflected in the recipe
https://github.com/conda-forge/typing_extensions-feedstock/pull/28
https://github.com/conda-forge/typing_extensions-feedstock/blob/main/recipe/meta.yaml#L21-L26

### Installed packages

```shell
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
importlib-metadata        4.8.1            py36ha15d459_0    conda-forge
importlib_metadata        4.8.1                hd8ed1ab_1    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
more-itertools            8.12.0             pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py36ha15d459_1    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pytest                    6.2.5            py36ha15d459_0    conda-forge
python                    3.6.13               h3758d61_0    https://repo.anaconda.com/pkgs/main
python_abi                3.6                     2_cp36m    conda-forge
sqlite                    3.38.2               h2bbff1b_0    https://repo.anaconda.com/pkgs/main
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
typing_extensions         4.2.0              pyha770c72_0    conda-forge
vc                        14.2                 h21ff451_1    https://repo.anaconda.com/pkgs/main
vs2015_runtime            14.27.29016          h5e58377_2    https://repo.anaconda.com/pkgs/main
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
```

### Environment info

```shell
active environment : broken-package
    active env location : C:\Users\tlam\anaconda3\envs\broken-package
            shell level : 2
       user config file : C:\Users\tlam\.condarc
 populated config files : C:\Users\tlam\.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.5=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\tlam\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64 
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64 
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\tlam\anaconda3\pkgs
                          C:\Users\tlam\.conda\pkgs
                          C:\Users\tlam\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\tlam\anaconda3\envs
                          C:\Users\tlam\.conda\envs
                          C:\Users\tlam\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by maximlt**
Fixes #29 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maximlt** [comment]
@conda-forge-admin please rerender

**Comment by maximlt** [comment]
@djsutherland @synapticarbors what do you think about that?

**Comment by jbednar** [comment]
@djsutherland @synapticarbors , if I understand how this all works, having build 0 of typing_extensions-4.2.0 still available at https://anaconda.org/conda-forge/typing_extensions/4.2.0/download/noarch/typing_extensions-4.2.0-pyha770c72_0.tar.bz2 will still cause py36 builds of projects like Datashader to fail, because even though build1 is available, conda will fall back to build 0 on py36, instead of falling back to 4.1.1 on py36 as it should. 

To fix that seems like ttps://anaconda.org/conda-forge/typing_extensions/4.2.0/download/noarch/typing_extensions-4.2.0-pyha770c72_0.tar.bz2 should be deleted, which will unfortunately break any envt that pinned that particular build (even on py37+ where there is no problem), or the repodata.json should be updated to declare that file incompatible with p36. Given the relatively short time that build 0 was available I personally would vote for simply deleting it.

**Comment by synapticarbors** [comment]
The correct way to remove it is described here:
https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages

Would you be willing to open the PR? If not, I can try to get to it sometime next week.

**Comment by jbednar** [comment]
Whew! It would be very useful for me to learn how to patch the repodata, but skimming the PRs to find similar examples makes it clear that will take me some time, and I'm trying to release Datashader today, so I don't think my brain can hold it right now. Maxime worked around it on our side for now, but it will still affect other projects, so this is still highly relevant to any other project still supporting py36, and I hope you'll be able to address it for their sake. Thanks!

**Comment by synapticarbors** [comment]
I opened a repodata patch in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/253. I'm not 100% sure if I did this correctly, but hopefully will get feedback if I didn't.

**Comment by jbednar** [comment]
Thanks! Looks reasonable to me, but so would an incorrect patch I think. :-)

**Pull request merged**
